### PR TITLE
restructure folders

### PR DESCRIPTION
**Pull request by MimaoQiuQiu**
Hi, I just did some restructuring, I need some advice to see if this is better than before.
api folder: where all API related files located
assets folder: all the resources
component: all reusable components
context: context(nothing for now)
hooks: all reusable custom hooks
pages: all the pages, currently it means the screens from Figma file. 
styles: all the stylings

Inside the component folder, there are different folders for every component, same thing for the pages folder. 

Now I'm fixing the profile setup page.

### CODE REVIEW

**Review by goodylove — COMMENTED** [review]
this is  more organized now. Thanks for this.

**Comment by abu-hasib** [comment]
Nice job. Though I will suggest moving out all the folders from the src folder.
I noticed you did not add an '/app' folder, I suggest we use it to have seamless routes management.
https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#migrating-from-pages-to-app

**Comment by MimaoQiuQiu** [comment]
I think you can try to create a new branch with your modifications and
create a new pull request. It can be merged after someone else approve it.

Ridwan Abiola ***@***.***>于2023年7月17日 周一13:21写道：

**Comment by abu-hasib** [comment]
Yes, I created a new branch but I get the write access error if I try to push it.

**Review by sgarciahelguera — APPROVED** [review]
Looks good to me

**Comment by sgarciahelguera** [comment]
> @MimaoQiuQiu How can I get write access to the repo? I'm getting write access error.

Hi, you should add yourself to the members spreadsheet, add at least your github account and discord account names.
From that I can give you write access

**Pull request merged**
